services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: directories_app
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
            - rabbitmq
            - minio
        environment:
            PHP_MEMORY_LIMIT: 512M

    web:
        image: nginx:1.25-alpine
        container_name: directories_web
        ports:
            - "8095:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

    db:
        image: postgres:15
        container_name: directories_db
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
        ports:
            - "5435:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U app -d app || exit 1"]
            interval: 5s
            timeout: 3s
            retries: 20

    pgadmin:
        image: dpage/pgadmin4:8
        container_name: directories_pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5051:80"
        depends_on:
            - db

    rabbitmq:
        image: rabbitmq:3-management
        container_name: directories_rabbitmq
        ports:
            - "5673:5672"
            - "15673:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq

    minio:
        image: minio/minio:latest
        container_name: directories_minio
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        ports:
            - "9010:9000"
            - "9011:9001"
        volumes:
            - minio-data:/data

volumes:
    db-data:
    rabbitmq-data:
    minio-data:
